# sendmail.py
fromStmp = ''           # 发件人邮箱的STMP服务器
fromEmail = ''          # 发件人的地址
fromPassword = ''       # 发件人的密码
toEmail = ''            # 收件信箱
path7z = ''             # 7zip的安装路径

# xk.py
idnumber = ''               # 学号
idpasswd = ''               # 密码
xk_term = '2018-2019-2'     # 学期
xk_interval = '10'          # 提交间隔
xk_list = [                 # 课程列表
    'a 00000000 01 notes',
    'd 00000000 01 other notes'
]

# jwc.py [仅作程序日志用]
